### ISSUE TITLE
Crossovers in .cljc files not supported

### ISSUE THREAD

**Issue by luposlip** [lshift/cloverage#120]
I have crossovers written for both Clojure and ClojureScript and stored in `.cljc` files. These don't seem to be recognized by cloverage (the file is called `company/common/utilities/core.cljc`):

```
Caused by: java.lang.IllegalArgumentException: Cannot find resource company/common/utilities/core.clj
       	at cloverage.source$resource_reader.invokeStatic(source.clj:20)
       	at cloverage.source$resource_reader.invoke(source.clj:15)
       	at cloverage.source$form_reader.invokeStatic(source.clj:23)
       	at cloverage.source$form_reader.invoke(source.clj:22)
       	at cloverage.source$ns_form.invokeStatic(source.clj:33)
       	at cloverage.source$ns_form.invoke(source.clj:32)
       	at cloverage.dependency$in_dependency_order$fn__1730.invoke(dependency.clj:69)
       	at clojure.core$map$fn__6631.invoke(core.clj:2727)
       	at clojure.lang.LazySeq.sval(LazySeq.java:40)
       	at clojure.lang.LazySeq.seq(LazySeq.java:49)
       	at clojure.lang.Cons.next(Cons.java:39)
       	at clojure.lang.RT.next(RT.java:703)
       	at clojure.core$next__6156.invokeStatic(core.clj:64)
       	at clojure.core.protocols$fn__8889.invokeStatic(protocols.clj:168)
       	at clojure.core.protocols$fn__8889.invoke(protocols.clj:124)
       	at clojure.core.protocols$fn__8844$G__8839__8853.invoke(protocols.clj:19)
       	at clojure.core.protocols$seq_reduce.invokeStatic(protocols.clj:31)
       	at clojure.core.protocols$fn__8872.invokeStatic(protocols.clj:75)
       	at clojure.core.protocols$fn__8872.invoke(protocols.clj:75)
       	at clojure.core.protocols$fn__8818$G__8813__8831.invoke(protocols.clj:13)
       	at clojure.core$reduce.invokeStatic(core.clj:6703)
       	at clojure.core$into.invokeStatic(core.clj:6768)
       	at clojure.core$into.invoke(core.clj:6762)
       	at cloverage.dependency$dependency_sort.invokeStatic(dependency.clj:62)
       	at cloverage.dependency$dependency_sort.invoke(dependency.clj:58)
       	at cloverage.dependency$in_dependency_order.invokeStatic(dependency.clj:69)
       	at cloverage.dependency$in_dependency_order.invoke(dependency.clj:65)
       	at cloverage.coverage$_main.invokeStatic(coverage.clj:171)
       	at cloverage.coverage$_main.doInvoke(coverage.clj:138)
       	at clojure.lang.RestFn.invoke(RestFn.java:3659)
       	at clojure.lang.Var.invoke(Var.java:649)
       	at user$eval15.invokeStatic(form-init2784252597013158593.clj:1)
       	at user$eval15.invoke(form-init2784252597013158593.clj:1)
       	at clojure.lang.Compiler.eval(Compiler.java:6946)
       	at clojure.lang.Compiler.eval(Compiler.java:6936)
       	at clojure.lang.Compiler.load(Compiler.java:7398)
       	... 14 more
```

**Comment by rm-hull** [comment]
I think this will be solved by #92 and/or #93 - I can't remember which order they got merged, but we. Are just awaiting a release to fix this.

@lvh - think this can be closed as a dupe

**Comment by luposlip** [comment]
Seems probable. I'll wait for @lvh to close it.

**Comment by lvh** [comment]
@luposlip Pending that, you can solve the issue by calling cloverage as: `CLOVERAGE_VERSION=1.0.7-SNAPSHOT lein cloverage` .

**Comment by luposlip** [comment]
Tnx!

Den ons. 24. aug. 2016 23.04 skrev lvh <notifications@github.com>:
