### ISSUE TITLE
Cloverage doesn't like Aleph

### ISSUE THREAD

**Issue by venantius** [lshift/cloverage#85]
Trying to run Cloverage on my service using [Aleph](https://github.com/ztellman/aleph) as an http server causes Cloverage to crash with the following exception:

```clojure
Exception in thread "main" java.lang.Exception: Couldn't eval form (cloverage.instrument/wrapm cloverage.coverage/track-coverage 1 ^{:line 1, :column 1, :file "titan/server.clj"} (ns titan.server ^{:line 2, :column 3} (:require [aleph.http :as http] [clojure.tools.logging :as log] [ring.middleware.reload :refer [wrap-reload]] [titan.db :as db] [titan.server.nrepl :as nrepl])))
(do (cloverage.coverage/cover 1560) (do (clojure.core/in-ns (quote titan.server)) ((fn* loading__5340__auto__ ([] (. clojure.lang.Var (clojure.core/pushThreadBindings {clojure.lang.Compiler/LOADER (. (. loading__5340__auto__ getClass) getClassLoader)})) (try (clojure.core/refer (quote clojure.core)) (clojure.core/require (quote [aleph.http :as http]) (quote [clojure.tools.logging :as log]) (quote [ring.middleware.reload :refer [wrap-reload]]) (quote [titan.db :as db]) (quote [titan.server.nrepl :as nrepl])) (finally (. clojure.lang.Var (clojure.core/popThreadBindings))))))) (if (. (quote titan.server) equals (quote clojure.core)) nil (do (. clojure.lang.LockingTransaction (clojure.core/runInTransaction (fn* ([] (clojure.core/commute (clojure.core/deref (var clojure.core/*loaded-libs*)) clojure.core/conj (quote titan.server)))))) nil))))
(ns titan.server (:require [aleph.http :as http] [clojure.tools.logging :as log] [ring.middleware.reload :refer [wrap-reload]] [titan.db :as db] [titan.server.nrepl :as nrepl]))
, compiling:(/private/var/folders/wp/h32jhtvs6vqd988zd0z9bbtr0000gn/T/form-init7104701061726129675.clj:1:125)
	at clojure.lang.Compiler.load(Compiler.java:7239)
	at clojure.lang.Compiler.loadFile(Compiler.java:7165)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.Exception: Couldn't eval form (cloverage.instrument/wrapm cloverage.coverage/track-coverage 1 ^{:line 1, :column 1, :file "titan/server.clj"} (ns titan.server ^{:line 2, :column 3} (:require [aleph.http :as http] [clojure.tools.logging :as log] [ring.middleware.reload :refer [wrap-reload]] [titan.db :as db] [titan.server.nrepl :as nrepl])))
(do (cloverage.coverage/cover 1560) (do (clojure.core/in-ns (quote titan.server)) ((fn* loading__5340__auto__ ([] (. clojure.lang.Var (clojure.core/pushThreadBindings {clojure.lang.Compiler/LOADER (. (. loading__5340__auto__ getClass) getClassLoader)})) (try (clojure.core/refer (quote clojure.core)) (clojure.core/require (quote [aleph.http :as http]) (quote [clojure.tools.logging :as log]) (quote [ring.middleware.reload :refer [wrap-reload]]) (quote [titan.db :as db]) (quote [titan.server.nrepl :as nrepl])) (finally (. clojure.lang.Var (clojure.core/popThreadBindings))))))) (if (. (quote titan.server) equals (quote clojure.core)) nil (do (. clojure.lang.LockingTransaction (clojure.core/runInTransaction (fn* ([] (clojure.core/commute (clojure.core/deref (var clojure.core/*loaded-libs*)) clojure.core/conj (quote titan.server)))))) nil))))
(ns titan.server (:require [aleph.http :as http] [clojure.tools.logging :as log] [ring.middleware.reload :refer [wrap-reload]] [titan.db :as db] [titan.server.nrepl :as nrepl]))

	at cloverage.instrument$instrument$fn__1939.invoke(instrument.clj:421)
	at cloverage.instrument$instrument.invoke(instrument.clj:413)
	at cloverage.coverage$_main$fn__3620.invoke(coverage.clj:175)
	at cloverage.coverage$_main.doInvoke(coverage.clj:172)
	at clojure.lang.RestFn.invoke(RestFn.java:3204)
	at clojure.lang.Var.invoke(Var.java:624)
	at user$eval1288.invoke(form-init7104701061726129675.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	... 11 more
Caused by: java.lang.IllegalArgumentException: Can't call nil, compiling:(aleph/http/client_middleware.clj:160:5)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6730)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at riddley.Util.localBinding(Util.java:9)
	at riddley.compiler$register_local$fn__1618.invoke(compiler.clj:63)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at riddley.compiler$register_local.invoke(compiler.clj:57)
	at riddley.walk$let_bindings$fn__1663.invoke(walk.clj:100)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.boundedLength(RT.java:1735)
	at clojure.lang.RestFn.applyTo(RestFn.java:130)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$mapcat.doInvoke(core.clj:2660)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at riddley.walk$let_bindings.invoke(walk.clj:97)
	at riddley.walk$let_handler$fn__1704.invoke(walk.clj:136)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at riddley.walk$let_handler.invoke(walk.clj:132)
	at riddley.walk$walk_exprs$fn__1719.invoke(walk.clj:185)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:630)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1868)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at riddley.walk$walk_exprs.invoke(walk.clj:176)
	at riddley.walk$walk_exprs.invoke(walk.clj:174)
	at manifold.deferred$back_references.invoke(deferred.clj:1181)
	at manifold.deferred$expand_let_flow$fn__20140.invoke(deferred.clj:1210)
	at clojure.core$map$fn__4557.invoke(core.clj:2629)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:674)
	at clojure.core$next__4112.invoke(core.clj:64)
	at clojure.core$zipmap.invoke(core.clj:2951)
	at manifold.deferred$expand_let_flow.invoke(deferred.clj:1198)
	at manifold.deferred$let_flow.doInvoke(deferred.clj:1258)
	at clojure.lang.RestFn.invoke(RestFn.java:467)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.lang.Compiler.macroexpand1(Compiler.java:6631)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6709)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5861)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5296)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3925)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6721)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6711)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:577)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6723)
	at clojure.lang.Compiler.analyze(Compiler.java:6524)
	at clojure.lang.Compiler.analyze(Compiler.java:6485)
	at clojure.lang.Compiler.eval(Compiler.java:6786)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:551)
	at aleph.http.client$eval23471$loading__5340__auto____23472.invoke(client.clj:1)
	at aleph.http.client$eval23471.invoke(client.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6771)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5753)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at aleph.http$eval12754$loading__5340__auto____12755.invoke(http.clj:1)
	at aleph.http$eval12754.invoke(http.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6771)
	at clojure.lang.Compiler.load(Compiler.java:7227)
	at clojure.lang.RT.loadResourceScript(RT.java:371)
	at clojure.lang.RT.loadResourceScript(RT.java:362)
	at clojure.lang.RT.load(RT.java:446)
	at clojure.lang.RT.load(RT.java:412)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:482)
	at titan.server$eval12748$loading__5340__auto____12749.invoke(titan/server.clj:1)
	at titan.server$eval12748.invoke(titan/server.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6782)
	at clojure.lang.Compiler.eval(Compiler.java:6771)
	at clojure.lang.Compiler.eval(Compiler.java:6772)
	at clojure.lang.Compiler.eval(Compiler.java:6745)
	at clojure.core$eval.invoke(core.clj:3081)
	at cloverage.instrument$instrument$fn__1939$fn__1940.invoke(instrument.clj:416)
	at cloverage.instrument$instrument$fn__1939.invoke(instrument.clj:414)
	... 20 more
Caused by: java.lang.IllegalArgumentException: Can't call nil
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6715)
	... 167 more
```

I've narrowed this down to the pure `require` statement -- even having this in a project namespace causes the above error, regardless of whether anything else in particular from Aleph was in use or not:

```clojure
  (:require [aleph.http :as http])
```

cc @ztellman in case he's run into this sort of thing before with other static analysis tools on Aleph. 

Cursory look suggests it's a problem of the analyzer choking on another static analyzer, but I could be wrong.

**Comment by arrdem** [comment]
It looks like this is a bug in the analyzer's handling of the `do` form at the top level. I get a similar failure when attempting to analyze usages of my guten-tag library which emits problematic top level do forms.
